# Generated by Django 3.1.1 on 2020-10-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='categories',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='starting_bid',
        ),
    ]
