# Generated by Django 3.1.1 on 2020-10-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
    ]
