# Generated by Django 3.1.1 on 2020-10-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='created_by',
            new_name='user',
        ),
    ]
